### ISSUE TITLE
Внедрить конечные автоматы в тикет

### ISSUE THREAD

**Issue by apavlyut** [apavlyut/geekstickets#13]
У нас должны быть статусы, управляться должны при помощи state_machine гема https://github.com/pluginaweek/state_machine

Тикет может быть:
1. Новый необработанный
2. Обработан, решение в проработке
3. Решение пердоставлено, ждем акцепта автора тикета
4. Акцепт получен | спорные моменты (ветвление статуса)
5. Тикет поставлен в график работы, дата релиза тогда-то
6. Результаты готовы, можно проверять
7. Тикет принят | спорные моменты (ветвление статуса)
8. Работа принята
9. Тикет резолвен.
10. Тикет отменен + причина закрытия.

Данные действия совершает каждая роль - сам фрилансер и клиент соотвественно.

Go code!

**Comment by VladFiliucov** [comment]
Беру)

**Comment by VladFiliucov** [comment]
стоп, а role based authorisation у нас уже есть разве?

**Comment by apavlyut** [comment]
go go!
