### ISSUE TITLE
Сделать slack интеграцию о добавлении нового тикета в систему

### ISSUE THREAD

**Issue by apavlyut** [apavlyut/geekstickets#6]
Предлагаю этот гем https://github.com/stevenosloan/slack-notifier

Хуки - на успешное создание тикета со ссылкой на него.

**Comment by EvanBrightside** [comment]
Забираю

**Comment by EvanBrightside** [comment]
Готово.

**Comment by apavlyut** [comment]
Когда делаешь пул реквест - указывай номер issue в коммит мессадже - #6 и после мерджа он закроет тикет.
