### ISSUE TITLE
Комментарии к тикетам

### ISSUE THREAD

**Issue by apavlyut** [apavlyut/geekstickets#7]
Нужно добавить комметирование к тикетам.

**Comment by VladFiliucov** [comment]
забираю

**Comment by VladFiliucov** [comment]
готово.

**Comment by apavlyut** [comment]
Ты когда закрываешь коммит - пиши #7 (это номер issue) - тогда она автоматом закроется.

**Comment by apavlyut** [comment]
Я гляну вечером и закрою issue
