### ISSUE TITLE
Добавить авторизацию в приложение

### ISSUE THREAD

**Issue by apavlyut** [apavlyut/geekstickets#9]
Использовать для этого pundit.

Кто забирает тикет пишет мне в slack за подробностями.

Результат выполнения задач - мы имеем возможность в приложении делать restricted ресурсы и политики доступа. 

Сделать на примере комментариев:
1. Читать могут все абсолютно даже гости,
2. Писать комментарии и добавлять тикеты могут только авторизованные пользователи.

**Comment by anatoly331** [comment]
беру

**Comment by apavlyut** [comment]
Как тут дела - готово или нет еще?

**Comment by apavlyut** [comment]
Беру
